### ISSUE TITLE
Fix 4 Security, 1 Maintainability issues in src\cogs\tickets.py

### ISSUE THREAD

**Issue by ZerXGIT** [Kenexar/kenexareu-bot#2]
[CodeFactor](https://www.codefactor.io/repository/github/kenexar/kenexareu-bot/overview/master) found multiple issues:

#### Possible SQL injection vector through string-based query construction.
- [ ]  [src\cogs\tickets.py:46-47](https://www.codefactor.io/repository/github/kenexar/kenexareu-bot/source/master/src/cogs/tickets.py#L46)
- [ ]  [src\cogs\tickets.py:41](https://www.codefactor.io/repository/github/kenexar/kenexareu-bot/source/master/src/cogs/tickets.py#L41)
- [ ]  [src\cogs\tickets.py:36](https://www.codefactor.io/repository/github/kenexar/kenexareu-bot/source/master/src/cogs/tickets.py#L36)
- [ ]  [src\cogs\tickets.py:31](https://www.codefactor.io/repository/github/kenexar/kenexareu-bot/source/master/src/cogs/tickets.py#L31)

#### Todo:
- [ ]  [src\cogs\tickets.py:14](https://www.codefactor.io/repository/github/kenexar/kenexareu-bot/source/master/src/cogs/tickets.py#L14)
